//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("DemoEmpleadosModel", "FK_TipoContracto", "tipoContracto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EmpleadosMVC.Models.TipoContracto), "empleado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EmpleadosMVC.Models.Empleado), true)]

#endregion

namespace EmpleadosMVC.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class DemoEmpleadosEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto DemoEmpleadosEntities usando la cadena de conexión encontrada en la sección 'DemoEmpleadosEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public DemoEmpleadosEntities() : base("name=DemoEmpleadosEntities", "DemoEmpleadosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DemoEmpleadosEntities.
        /// </summary>
        public DemoEmpleadosEntities(string connectionString) : base(connectionString, "DemoEmpleadosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DemoEmpleadosEntities.
        /// </summary>
        public DemoEmpleadosEntities(EntityConnection connection) : base(connection, "DemoEmpleadosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Empleado> EmpleadoSet
        {
            get
            {
                if ((_EmpleadoSet == null))
                {
                    _EmpleadoSet = base.CreateObjectSet<Empleado>("EmpleadoSet");
                }
                return _EmpleadoSet;
            }
        }
        private ObjectSet<Empleado> _EmpleadoSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TipoContracto> TipoContractoSet
        {
            get
            {
                if ((_TipoContractoSet == null))
                {
                    _TipoContractoSet = base.CreateObjectSet<TipoContracto>("TipoContractoSet");
                }
                return _TipoContractoSet;
            }
        }
        private ObjectSet<TipoContracto> _TipoContractoSet;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet EmpleadoSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEmpleadoSet(Empleado empleado)
        {
            base.AddObject("EmpleadoSet", empleado);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TipoContractoSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTipoContractoSet(TipoContracto tipoContracto)
        {
            base.AddObject("TipoContractoSet", tipoContracto);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoEmpleadosModel", Name="Empleado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Empleado : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Empleado.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        /// <param name="dNI">Valor inicial de la propiedad DNI.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="sueldo">Valor inicial de la propiedad Sueldo.</param>
        /// <param name="sueldoAnual">Valor inicial de la propiedad SueldoAnual.</param>
        /// <param name="estatus">Valor inicial de la propiedad Estatus.</param>
        /// <param name="iDTipo">Valor inicial de la propiedad IDTipo.</param>
        public static Empleado CreateEmpleado(global::System.Int32 id, global::System.String dNI, global::System.String nombre, global::System.Double sueldo, global::System.Double sueldoAnual, global::System.Int32 estatus, global::System.Int32 iDTipo)
        {
            Empleado empleado = new Empleado();
            empleado.ID = id;
            empleado.DNI = dNI;
            empleado.Nombre = nombre;
            empleado.Sueldo = sueldo;
            empleado.SueldoAnual = sueldoAnual;
            empleado.Estatus = estatus;
            empleado.IDTipo = iDTipo;
            return empleado;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DNI
        {
            get
            {
                return _DNI;
            }
            set
            {
                OnDNIChanging(value);
                ReportPropertyChanging("DNI");
                _DNI = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DNI");
                OnDNIChanged();
            }
        }
        private global::System.String _DNI;
        partial void OnDNIChanging(global::System.String value);
        partial void OnDNIChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Sueldo
        {
            get
            {
                return _Sueldo;
            }
            set
            {
                OnSueldoChanging(value);
                ReportPropertyChanging("Sueldo");
                _Sueldo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sueldo");
                OnSueldoChanged();
            }
        }
        private global::System.Double _Sueldo;
        partial void OnSueldoChanging(global::System.Double value);
        partial void OnSueldoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double SueldoAnual
        {
            get
            {
                return _SueldoAnual;
            }
            set
            {
                OnSueldoAnualChanging(value);
                ReportPropertyChanging("SueldoAnual");
                _SueldoAnual = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SueldoAnual");
                OnSueldoAnualChanged();
            }
        }
        private global::System.Double _SueldoAnual;
        partial void OnSueldoAnualChanging(global::System.Double value);
        partial void OnSueldoAnualChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estatus
        {
            get
            {
                return _Estatus;
            }
            set
            {
                OnEstatusChanging(value);
                ReportPropertyChanging("Estatus");
                _Estatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Estatus");
                OnEstatusChanged();
            }
        }
        private global::System.Int32 _Estatus;
        partial void OnEstatusChanging(global::System.Int32 value);
        partial void OnEstatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDTipo
        {
            get
            {
                return _IDTipo;
            }
            set
            {
                OnIDTipoChanging(value);
                ReportPropertyChanging("IDTipo");
                _IDTipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDTipo");
                OnIDTipoChanged();
            }
        }
        private global::System.Int32 _IDTipo;
        partial void OnIDTipoChanging(global::System.Int32 value);
        partial void OnIDTipoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoEmpleadosModel", "FK_TipoContracto", "tipoContracto")]
        public TipoContracto TipoContracto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoContracto>("DemoEmpleadosModel.FK_TipoContracto", "tipoContracto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoContracto>("DemoEmpleadosModel.FK_TipoContracto", "tipoContracto").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoContracto> TipoContractoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoContracto>("DemoEmpleadosModel.FK_TipoContracto", "tipoContracto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoContracto>("DemoEmpleadosModel.FK_TipoContracto", "tipoContracto", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoEmpleadosModel", Name="TipoContracto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoContracto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TipoContracto.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        /// <param name="estatus">Valor inicial de la propiedad Estatus.</param>
        public static TipoContracto CreateTipoContracto(global::System.Int32 id, global::System.Int32 estatus)
        {
            TipoContracto tipoContracto = new TipoContracto();
            tipoContracto.ID = id;
            tipoContracto.Estatus = estatus;
            return tipoContracto;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MultiploAnual
        {
            get
            {
                return _MultiploAnual;
            }
            set
            {
                OnMultiploAnualChanging(value);
                ReportPropertyChanging("MultiploAnual");
                _MultiploAnual = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MultiploAnual");
                OnMultiploAnualChanged();
            }
        }
        private Nullable<global::System.Int32> _MultiploAnual;
        partial void OnMultiploAnualChanging(Nullable<global::System.Int32> value);
        partial void OnMultiploAnualChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estatus
        {
            get
            {
                return _Estatus;
            }
            set
            {
                OnEstatusChanging(value);
                ReportPropertyChanging("Estatus");
                _Estatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Estatus");
                OnEstatusChanged();
            }
        }
        private global::System.Int32 _Estatus;
        partial void OnEstatusChanging(global::System.Int32 value);
        partial void OnEstatusChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoEmpleadosModel", "FK_TipoContracto", "empleado")]
        public EntityCollection<Empleado> Empleados
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Empleado>("DemoEmpleadosModel.FK_TipoContracto", "empleado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Empleado>("DemoEmpleadosModel.FK_TipoContracto", "empleado", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
